services:
  auth:
    build:
      context: .
      dockerfile: ./build/auth-service-Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_PORT=8080
      - AUTH_SIGNING_KEY=c423f43952016ab0d7696b8d35b16e6f07888838dda4405987e36116ee78a620
  todo:
    build:
      context: .
      dockerfile: ./build/todo-service-Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - auth
    environment:
      - TODO_PORT=9090
      - AUTH_SIGNING_KEY=c423f43952016ab0d7696b8d35b16e6f07888838dda4405987e36116ee78a620